version: 2.1

executors:
  ubuntu:
    docker:
      - image: iamsomeone2/ubuntu-cmake:latest
        auth:
          username: iamsomeone2
          password: $docker_password
  fedora:
    docker:
      - image: iamsomeone2/pgsplusplus_build:fedora-latest
        auth:
          username: iamsomeone2
          password: $docker_password
jobs:
  fedora_33-build_and_test:
    executor: fedora

    steps:
      # Deal with source set up
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - restore_cache:
          keys: 
            - test-resources-{{ .Branch }}
            - test-resources

      - run:
          name: 'Retrieve test resources'
          command: |
            cd test/res
            wget -nc -O test_resources.tar.xz "https://onedrive.live.com/download?cid=3ACEA36CBA105F99&resid=3ACEA36CBA105F99%2112023&authkey=AEb0x9TqgVsT4_M"
            tar -xJvf test_resources.tar.xz
            rm test_resources.tar.xz
      
      - save_cache:
          key: test-resources-{{ .Branch }}
          paths:
            - "test/res/subs.sup"
            - "test/res/subs_short.sup"

      - run:
          name: 'Set up build environment'
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=on ..

      - run:
          name: 'Build Pgs++'
          command: |
            cd build
            make -j$(nproc)

      - run:
          name: 'Execute tests'
          command: |
            cd build
            mkdir test-results
            make test > test-results/results.txt

      # Store working directory
      - persist_to_workspace:
          root: ./
          paths:
            - ./*

      - store_artifacts:
          path: build/test-results
          destination: test-results

      - store_test_results:
          path: build/test-results

  fedora_33-package:
    executor: fedora

    steps:
      - attach_workspace:
          at: ./

      # CMake config should already be complete from the previous job
      - restore_cache:
          keys:
            - tarball-{{ .Branch }}-{{ .Revision }}
            - tarball-{{ .Branch }}-

      - run:
          name: 'Generate source pacakge'
          command: |
            chmod +x dist/redhat/pack_for_rpm.sh
            dist/redhat/pack_for_rpm.sh
            mv v1.0.0.tar.gz /home/circleci/rpmbuild/SOURCES/

      - save_cache:
          key: tarball-{{ .Branch }}-{{ .Revision }}
          paths:
            - "/home/circleci/rpmbuild/SOURCES/v1.0.0.tar.gz"

      - run:
          name: 'Move SPEC file to rpmbuild dirs'
          command: |
            cp dist/redhat/pgs++.spec ~/rpmbuild/SPECS
    
      # Project must still be rebuilt to be packaged
      - run:
          name: 'Create RPM packages'
          command: |
            rpmbuild -bb /home/circleci/rpmbuild/SPECS/pgs++.spec

      - store_artifacts:
          path: /home/circleci/rpmbuild/RPMS/
          destination: RPMs

workflows:
  fedora_33:
    jobs:
      - fedora_33-build_and_test
      - fedora_33-package:
          requires:
            - fedora_33-build_and_test
