version: 2.1

jobs:
  build:
    docker:
      # Base Ubuntu 20.04 image used for hosting other containers.
      - image: cimg/base:stable-20.04
    
      # Secondary container used for building RPMs
      - image: fedora:latest

    steps:
      # Deal with source set up
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - run:
          name: 'Install build dependencies'
          command: |
            sudo dnf install -y gcc-c++ cmake

      - run:
          name: 'Set up build environment'
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=off ..

      - run:
          name: 'Build libpgs'
          command: make -j$(nproc)
