version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable-20.04 # Basic Ubuntu 20.04 image
    
    steps:
      - checkout
      - run:
        - name: 'Get build dependencies'
        - command: sudo apt install cmake
      - run:
        - name: 'Set up build environment'
        - command: mkdir build && cd build
        - command: cmake -DCMAKE_BUILD_TYPE=Release ..
      - run:
        - name: 'Build libpgs'
        - command: make -j$(nproc)
