version: 2.1

executors:
  ubuntu:
    docker:
      # Base Ubuntu 20.04 image used for hosting other containers.
      - image: iamsomeone2/ubuntu-cmake:latest
        auth:
          username: iamsomeone2
          password: $docker_password
  fedora:
    docker:
      - image: iamsomeone2/cpp_base:fedora-latest
        auth:
          username: iamsomeone2
          password: $docker_password
jobs:
  build:
    executor: fedora

    steps:
      # Deal with source set up
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - run:
          name: 'Set up build environment'
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=off ..

      - run:
          name: 'Build Pgs++'
          command: |
            cd build
            make -j$(nproc)

  package:
    executor: fedora

    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - run:
          name: 'Set up build environment'
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=off ..

      - restore_cache:
          keys:
            - tarball-{{ .Branch }}-{{ .Revision }}
            - tarball-{{ .Branch }}-

      - run:
          name: 'Generate source pacakge'
          command: |
            chmod +x dist/redhat/pack_for_rpm.sh
            dist/redhat/pack_for_rpm.sh
            mv v0.1.0-alpha.tar.gz /home/circleci/rpmbuild/SOURCES/

      - save_cache:
          key: tarball-{{ .Branch }}-{{ .Revision }}
          paths:
            - "/home/circleci/rpmbuild/SOURCES/v0.1.0-alpha.tar.gz"

      - run:
          name: 'Move SPEC file to rpmbuild dirs'
          command: |
            cp dist/redhat/pgs++.spec ~/rpmbuild/SPECS
          
      - run:
          name: 'Create RPM packages'
          command: |
            rpmbuild -bb /home/circleci/rpmbuild/SPECS/pgs++.spec

      - store_artifacts:
          path: /home/circleci/rpmbuild/RPMS/
          destination: RPMs

workflows:
  build_and_pack:
    jobs:
      - build
      - package
